### PR TITLE
Add cache hints to info.cacheControl

### PR DESCRIPTION
**Pull request by ojkelly**
This is a small addition to expose the `cacheControl` hints to the resolvers at runtime.

- [x] feature
- [ ] blocking
- [ ] docs

### CODE REVIEW

**Comment by ojkelly** [comment]
Sorry I somehow managed to add the blocking label, this isn't blocking.

**Comment by martijnwalraven** [comment]
No problem, thanks for the PR. 

We want to be careful before adding to the public API, so I'm wondering if there's another way to accomplish what you're trying to do. What is your use case for exposing the hint?

**Comment by ojkelly** [comment]
I want to be able to add field level caching in the resolvers after an authorization check.

**Comment by martijnwalraven** [comment]
Hmmm, but isn't that what `addCacheHint`is for? Why isn't that working for you?

**Comment by ojkelly** [comment]
Not quite, I want to read the cache hints defined in the schema in the resolver, not set them.

So I can add additional caching only if an authorization check succeeds.

**Comment by martijnwalraven** [comment]
Do you mean you you want to add additional hints on top of the ones defined in the schema when the authorization check succeeds? `addCacheHint` will merge the new hint with the ones from the schema, so it seems like that should work for you?

**Comment by ojkelly** [comment]
No I want to be able to read the `cacheHint` defined on the schema in the resolver. i.e. I want to be able to use the value for `cacheHint` in the resolver.

In a resolver where `info.cacheControl.addCacheHint` lets you set additional cache hints, I want to be able to read `info.cacheControl.hints` and get the value of the currently set hint, to do additional caching outside that which is provided by the apollo cache service.

**Comment by martijnwalraven** [comment]
Ah, now I see what you mean! So what kind of caching are you looking to do on a per-resolver basis? (Interested because I'm working on partial query caching for Apollo Engine, so curious what you've landed on here.)

**Comment by ojkelly** [comment]
So this is very rough https://github.com/ojkelly/bunjil/blob/ok/caching/src/bunjil.ts#L280

Essentially after the schema's are finalised, all the resolvers are wrapped with another resolver function. That's the function I linked above.

In that function, it does an authorization check and either errors, or waits for the actual resolver to finish, and then returns the result.

So I want to wrap the actual resolver in a cache call, but only after the authn check, as I don't want any possibility of leaking data via a cache.

Right now the actual cache is just an in-memory one, but it would be something like memcached or redis, in production use.

**Comment by martijnwalraven** [comment]
Ah, so you're memoizing resolvers based on the cache hints, that makes sense.

Have you seen [schema directives](https://dev-blog.apollodata.com/reusable-graphql-schema-directives-131fb3a177d1)? Maybe that doesn't help here because you're doing this for every resolver, but if you need more control that could be a nice way of applying this kind of behavior on a per-field basis.

**Comment by ojkelly** [comment]
I did look at schema directives, but that would just overwrite everything `apollo-cache-control` does wouldn't it?

I was hoping to still have the ability to leverage Apollo Engine.

**Comment by martijnwalraven** [comment]
Oh, I meant as a way of conditionally applying authorization and memoization, not as a replacement for `@cacheControl`. So for instance maybe you could add `@authorize` or `@memoize` directives to selectively apply the behavior to fields. If you're doing this for every field, it's probably not much help.

Regardless of where you implement this, it seems in your case exposing `hint` is indeed what you need, so we should probably go ahead and expose it.

**Comment by ojkelly** [comment]
Yeah the way authn is implemented, its for every type and field, so every resolver.

I like the idea of `@memoize`, but I feel like it's implicit based on `@cacheControl`.

Thanks!

**Comment by martijnwalraven** [comment]
I wonder if `hint` should be `cacheHint` though, for consistency with `addCacheHint`. (In hindsight, that should probably have been `cacheControl.addHint`!)

**Comment by ojkelly** [comment]
I think for consistency you're right `cacheControl.cacheHint` matches the convention you've set, shall I update the PR?

**Comment by martijnwalraven** [comment]
Thanks!

**Comment by ojkelly** [comment]
Can I bump this to get a new release on npm?

Thanks!

**Pull request merged**
